[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[theme]
base="dark"
primaryColor="#22c55e"
backgroundColor="#0f172a"
secondaryBackgroundColor="#020617"
textColor="#e5e7eb"
font="sans serif"